# Veracode Policy Scan workflow. Requires the following secrets:
# VERACODE_API_ID - https://help.veracode.com/r/t_create_api_creds
# VERACODE_API_KEY - https://help.veracode.com/r/t_create_api_creds

name: Veracode Policy Scan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-policy-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
        with: 
          java-version: '8'

      - name: Compile for Veracode
        run: sbt 'set scalacOptions += "-g:vars"' compile package
        
      # zip the project and move it to a staging directory
      - name: Zip Project
        run: zip -R project.zip '*.jar' '*.war'
        env:
          build-name: project.zip      
        
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: CodePackage
          path: project.zip

      - uses: veracode/veracode-uploadandscan-action@master # Run the uploadandscan action. Inputs are described above.
        with:
          appname: '${{ github.event.repository.name }}'
          filepath: 'project.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          scantimeout: 15
          createprofile: true
          version: 'Scan from Github job: ${{ github.run_id }}'
